export GOPATH=/Users/chen/gopath
export GOROOT=/Users/chen/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOBIN
#export DOCKER_HOST="tcp://127.0.0.1:2375"
#export ETCD_HOST=$(echo $DOCKER_HOST|cut -d'/' -f3|cut -d: -f1):4001
export D1CLIENT=$GOPATH/src/code.ccplaying.com/d1/client
export MGO="127.0.0.1"
